# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build docker container
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run docker build
        run: docker build -t test_django .
        
      # Runs a single command using the runners shell
      - name: Drop old container
        run: docker rm test_django

      # Runs a set of commands using the runners shell
      - name: Tests
        run: |
          docker run --name test_django -p 8080:8080 test_django python3 manage.py test

  deploy:
    name: Deploy
    needs: [ build ]
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy
        run: |
          docker run --name test_django -p 8080:8080 -d test_django

