# This is a basic workflow to help you get started with Actions

name: Merge CD
on:
  pull_request:
    types:
      - closed
    branches:
      - "main"
  workflow_dispatch:

jobs:
  print_info:
    name: print info
    runs-on: self-hosted
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
    steps:
    - run: |
        echo ${{github.event.pull_request.merged}}
        echo ${{ toJson(github.event.pull_request.merged) }}
        echo "$GITHUB_CONTEXT"

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
    - run: |
        echo The PR was merged
